import { deepResearchSchema } from '@/lib/research-framework';
const sourceSchema = {
  type: 'object',
  properties: {
    title: { type: 'string' },
    publisher: { type: 'string' },
    url: { type: 'string' },
    date: { type: 'string' },
  },
  required: ['title', 'publisher', 'url', 'date'],
  additionalProperties: false,
};

export const companySchema = {
  type: 'object',
  properties: {
    companyName: { type: 'string' },
    companyCode: { type: 'string' },
    exchange: { type: 'string' },
    industry: { type: 'string' },
    updatedAt: { type: 'string' },
    quote: {
      type: 'object',
      properties: {
        price: { type: 'string' },
        change: { type: 'string' },
        currency: { type: 'string' },
        marketCap: { type: 'string' },
        asOf: { type: 'string' },
      },
      required: ['price', 'change', 'currency', 'marketCap', 'asOf'],
      additionalProperties: false,
    },
    thesis: { type: 'string' },
    stance: { type: 'string', enum: ['积极', '中性', '谨慎'] },
    overview: { type: 'string' },
    metrics: {
      type: 'array',
      minItems: 0,
      maxItems: 6,
      items: {
        type: 'object',
        properties: {
          label: { type: 'string' },
          value: { type: 'string' },
          period: { type: 'string' },
          change: { type: 'string' },
          assessment: { type: 'string' },
          sourceUrl: { type: 'string' },
        },
        required: [
          'label',
          'value',
          'period',
          'change',
          'assessment',
          'sourceUrl',
        ],
        additionalProperties: false,
      },
    },
    factors: {
      type: 'array',
      minItems: 5,
      maxItems: 5,
      items: {
        type: 'object',
        properties: {
          category: {
            type: 'string',
            enum: ['政策', '行业', '资金', '财报', '宏观'],
          },
          signal: { type: 'string', enum: ['正面', '中性', '负面'] },
          title: { type: 'string' },
          summary: { type: 'string' },
          evidence: {
            type: 'array',
            minItems: 0,
            maxItems: 1,
            items: {
              type: 'object',
              properties: {
                label: { type: 'string' },
                value: { type: 'string' },
                sourceName: { type: 'string' },
                sourceUrl: { type: 'string' },
                date: { type: 'string' },
              },
              required: ['label', 'value', 'sourceName', 'sourceUrl', 'date'],
              additionalProperties: false,
            },
          },
        },
        required: ['category', 'signal', 'title', 'summary', 'evidence'],
        additionalProperties: false,
      },
    },
    strengths: {
      type: 'array',
      minItems: 0,
      maxItems: 3,
      items: { type: 'string' },
    },
    risks: {
      type: 'array',
      minItems: 0,
      maxItems: 3,
      items: { type: 'string' },
    },
    catalysts: {
      type: 'array',
      minItems: 0,
      maxItems: 3,
      items: { type: 'string' },
    },
    conclusion: { type: 'string' },
    sources: { type: 'array', minItems: 0, maxItems: 30, items: sourceSchema },
    disclaimer: { type: 'string' },
    deepResearch: deepResearchSchema,
  },
  required: [
    'companyName',
    'companyCode',
    'exchange',
    'industry',
    'updatedAt',
    'quote',
    'thesis',
    'stance',
    'overview',
    'metrics',
    'factors',
    'strengths',
    'risks',
    'catalysts',
    'conclusion',
    'sources',
    'disclaimer',
    'deepResearch',
  ],
  additionalProperties: false,
};
